FROM node:20.10.0
WORKDIR /usr/src/app
COPY controllers /controllers
COPY middlewares /middlewares
COPY models /models
COPY routes /routes
COPY ./db/database.js ./db/database.js
COPY ./server.js ./server.js
COPY ./package.json ./package.json
RUN npm install -g npm
RUN npm install 
EXPOSE 3000
CMD ["node", "server.js"]